import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { createRequire } from 'node:module'
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync, existsSync, symlinkSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import test from 'node:test'
import { input, pipeline, placeholders, write, typecheck } from '../../../../newstyle_projects/projects/liana/sketch/temp/pipeline.mjs'
import * as api from '../../../../newstyle_projects/projects/liana/sketch/transformers/pareto_next_sketch/typescript/dist/modules/source.liana.generated/schemas/unresolved/refiners/list_of_characters.js'
import * as authoringSerializer from '../../../../newstyle_projects/projects/liana/sketch/transformers/pareto_next_sketch/typescript/dist/modules/source.liana.generated/schemas/unresolved/transformers/serialized_paragraph.js'
import { convert } from '../../../../newstyle_projects/projects/liana/sketch/temp/convert_registry.mjs'
import { sealedSchemaText } from './native_schema_text.mjs'
import { boekhoudingYears } from '../../../../liana-vscode/test/fixtures/boekhouding-years.mjs'
import { instanceTextNormalizer } from '../../../../newstyle_projects/tools/liana/instance_text.mjs'
import { Syntax_Lines } from '../../../../newstyle_projects/projects/liana/sketch/transformers/pareto_next_sketch/typescript/dist/transform.js'

const base = new URL('../../../../newstyle_projects/', import.meta.url)
const examples = new URL('projects/liana/sketch/examples/', base)
const require = createRequire(new URL('projects/liana/sketch/transformers/pareto_next_sketch/typescript/package.json', base))
const p = await import(require.resolve('pareto-core/transformer'))
const lookup = await import(require.resolve('pareto-core/refiner/specials/lookup'))
const abort = error => { throw error }
const chars = source => p.literal.list(Array.from(source, c => c.codePointAt(0)))
const entry = (dictionary, name) => p.from.dictionary(dictionary).get_possible_entry(name, value => value, () => assert.fail(name))
const fixture = name => input(fileURLToPath(new URL(name + '.liana.lna', examples)))
const compile = directory => {
    const configuration = join(directory, 'tsconfig.json')
    const config = JSON.parse(readFileSync(configuration, 'utf8'))
    config.compilerOptions.noEmit = false
    config.compilerOptions.outDir = 'dist'
    writeFileSync(configuration, JSON.stringify(config))
    execFileSync(process.execPath, [fileURLToPath(new URL('tools/typescript.cjs', base)), '-p', directory], { stdio: 'pipe' })
}

test('the canonical Liana API is generated by the new pipeline, with no semantic resolver for ASTN', () => {
    const generated = pipeline(fixture('liana'))
    assert.deepEqual(placeholders(generated.pareto), [])
    const apiPath = fileURLToPath(new URL('projects/liana/sketch/transformers/pareto_next_sketch/typescript/src/modules/source.liana.generated/', base))
    assert.ok(existsSync(join(apiPath, 'schemas/unresolved/schema.ts')))
    assert.equal(existsSync(join(apiPath, 'schemas/resolved')), false)
    assert.deepEqual(api.Root(chars("| astn ( imports: {} globals: ( 'simple types': {} ) types: { 'Root': ( 'root value': | nothing ~ ) } root: 'Root' )"),
        abort, { 'tab size': 4 })[0], 'astn')
})

test('ASTN API round-trips simple reference/id syntax and resolves inline imports without lookup placeholders', async () => {
    for (const name of ['identifiers', 'imports', 'data_formats--json']) {
        const directory = mkdtempSync(join(tmpdir(), 'liana-next-pipeline-'))
        try {
            const generated = pipeline(fixture(name))
            assert.deepEqual(placeholders(generated.pareto), [], name)
            assert.equal(entry(generated.pareto.schemas, 'unresolved').refiners.__get_raw().length, 2)
            assert.ok(!generated.pareto.schemas.__get_raw().some(([id]) => id === 'resolved'))
            const output = write(generated.typescript, directory)
            assert.equal(output.typescriptPlaceholders, 0)
            assert.deepEqual(typecheck(directory), { status: 'passed' })
            compile(directory)
            const parser = await import(pathToFileURL(join(directory, 'dist/schemas/unresolved/refiners/list_of_characters.js')))
            const serializer = await import(pathToFileURL(join(directory, 'dist/schemas/unresolved/transformers/serialized_paragraph.js')))
            if (name === 'identifiers') {
                const source = "( name: 'alice' target: 'bob' description: \"hello\" )"
                const value = parser.Root(chars(source), abort, { 'tab size': 4 })
                assert.deepEqual(value, { name: 'alice', target: 'bob', description: 'hello' })
                const rendered = serializer.Root(value, { indentation: '    ' }).__get_raw().join('\n')
                assert.match(rendered, /'alice'/)
                assert.match(rendered, /'bob'/)
                assert.match(rendered, /"hello"/)
                assert.deepEqual(parser.Root(chars(rendered), abort, { 'tab size': 4 }), value)
            } else if (name === 'imports') {
                assert.equal(parser.Root(chars("'alice'"), abort, { 'tab size': 4 }), 'alice')
                assert.equal(serializer.Root('alice', { indentation: '    ' }).__get_raw().join('\n'), "'alice'")
            } else {
                const value = parser.Root(chars('| string "hello"'), abort, { 'tab size': 4 })
                assert.deepEqual(value, ['string', 'hello'])
                assert.deepEqual(parser.Root(chars(serializer.Root(value, { indentation: '    ' }).__get_raw().join('\n')), abort, { 'tab size': 4 }), value)
            }
        } finally {
            rmSync(directory, { recursive: true })
        }
    }
})

test('semantic API exposes parsing and the declared resolver separately', async () => {
    const directory = mkdtempSync(join(tmpdir(), 'liana-next-semantic-'))
    try {
        const generated = pipeline(fixture('resolver'))
        const resolved = entry(generated.pareto.schemas, 'resolved')
        assert.ok(resolved.refiners.__get_raw().some(([id]) => id === 'unresolved'))
        assert.ok(!resolved.refiners.__get_raw().some(([id]) => id === 'list of characters'))
        write(generated.typescript, directory)
        assert.deepEqual(typecheck(directory), { status: 'passed' })
        compile(directory)
        const parser = await import(pathToFileURL(join(directory, 'dist/schemas/unresolved/refiners/list_of_characters.js')))
        const resolver = await import(pathToFileURL(join(directory, 'dist/schemas/resolved/refiners/unresolved.js')))
        assert.equal(resolver.Root(parser.Root(chars('"hello"'), abort, { 'tab size': 4 }), abort, null, null), 'hello')
    } finally {
        rmSync(directory, { recursive: true })
    }
})

test('Lioncore resolves language and entity references with explicit dependency kinds', async t => {
    const directory = mkdtempSync(join(tmpdir(), 'liana-next-lioncore-'))
    try {
        const source = fixture('lioncore')
        const root = entry(source[1].types, 'Root')['root value']
        assert.deepEqual(root[1].__get_raw().map(([id]) => id), ['languages', 'primary language'])
        assert.deepEqual(source[1].globals['simple types'].__get_raw().map(([id]) => id), ['boolean', 'version'])
        const generated = pipeline(source)
        assert.deepEqual(placeholders(generated.pareto), [])
        write(generated.typescript, directory)
        assert.deepEqual(typecheck(directory), { status: 'passed' })
        compile(directory)
        const parser = await import(pathToFileURL(join(directory, 'dist/schemas/unresolved/refiners/list_of_characters.js')))
        const resolver = await import(pathToFileURL(join(directory, 'dist/schemas/resolved/refiners/unresolved.js')))
        const serializer = await import(pathToFileURL(join(directory, 'dist/schemas/resolved/transformers/serialized_paragraph.js')))
        const parse = text => parser.Root(chars(text), abort, { 'tab size': 4 })
        const resolve = value => resolver.Root(value, abort, null, null)
        const plain = value => JSON.parse(JSON.stringify(value, (_key, item) =>
            item?.__dictionary ? { ...item, source: [...item.source].sort(([left], [right]) => left.localeCompare(right)) } : item))
        const present = value => p.from.optional(value).decide(value => value, () => assert.fail('Expected a present reference'))
        const authored = parse(`(
            languages: {
                'Main': (
                    version: "1"
                    \`depends on\`: { 'Base': 'Base' }
                    entities: {
                        'Person': | classifier (
                            features: {
                                'name': ( optional: false kind: | property ( type: | local ( entity: 'Text' ) ) )
                                'other': ( optional: true kind: | link (
                                    multiple: false type: | local ( entity: 'Other' ) kind: | reference ~
                                ) )
                                'children': ( optional: false kind: | link (
                                    multiple: true type: | external ( language: 'Base' entity: 'Node' ) kind: | containment ~
                                ) )
                            }
                            kind: | concept (
                                abstract: false partition: false
                                extends: * | local ( entity: 'Other' )
                                implements: [ | local ( entity: 'Interface' ) ]
                            )
                        )
                        'Note': | classifier (
                            features: {}
                            kind: | annotation (
                                annotates: * | local ( entity: 'Person' )
                                extends: * | external ( language: 'Base' entity: 'Annotation' )
                                implements: []
                            )
                        )
                        'Interface': | classifier (
                            features: {}
                            kind: | interface ( extends: [ | external ( language: 'Base' entity: 'Interface' ) ] )
                        )
                        'Record': | \`data type\` | \`structured data type\` (
                            fields: { 'value': ( type: | external ( language: 'Base' entity: 'Text' ) ) }
                        )
                        'Text': | \`data type\` | \`primitive type\` ~
                        'Other': | classifier (
                            features: {} kind: | concept ( abstract: false partition: false extends: _ implements: [] )
                        )
                    }
                )
                'Base': (
                    version: "1" \`depends on\`: {}
                    entities: {
                        'Text': | \`data type\` | \`primitive type\` ~
                        'Node': | classifier (
                            features: {} kind: | concept ( abstract: false partition: false extends: _ implements: [] )
                        )
                        'Interface': | classifier ( features: {} kind: | interface ( extends: [] ) )
                        'Annotation': | classifier (
                            features: {} kind: | annotation ( annotates: _ extends: _ implements: [] )
                        )
                    }
                )
            }
            \`primary language\`: 'Main'
        )`)

        await t.test('forward references preserve target identity and serialize back to identifiers', () => {
            const resolved = resolve(authored)
            const main = entry(resolved.languages, 'Main')
            const base = entry(resolved.languages, 'Base')
            const person = entry(main.entities, 'Person')[1]
            assert.equal(resolved['primary language']['l entry'], main)
            assert.equal(entry(main['depends on'], 'Base')['l entry'], base)
            assert.equal(entry(person.features, 'name').kind[1].type[1].entity['l entry'], entry(main.entities, 'Text'))
            assert.equal(entry(person.features, 'other').kind[1].type[1].entity['l entry'], entry(main.entities, 'Other'))
            const external = entry(person.features, 'children').kind[1].type[1]
            assert.equal(external.language['l entry'], entry(main['depends on'], 'Base'))
            assert.equal(external.entity['l entry'], entry(base.entities, 'Node'))
            assert.equal(present(person.kind[1].extends)[1].entity['l entry'], entry(main.entities, 'Other'))
            assert.equal(person.kind[1].implements.__get_raw()[0][1].entity['l entry'], entry(main.entities, 'Interface'))
            const note = entry(main.entities, 'Note')[1].kind[1]
            assert.equal(present(note.annotates)[1].entity['l entry'], entry(main.entities, 'Person'))
            assert.equal(present(note.extends)[1].entity['l entry'], entry(base.entities, 'Annotation'))
            const iface = entry(main.entities, 'Interface')[1].kind[1]
            assert.equal(iface.extends.__get_raw()[0][1].entity['l entry'], entry(base.entities, 'Interface'))
            const record = entry(main.entities, 'Record')[1][1]
            assert.equal(entry(record.fields, 'value').type[1].entity['l entry'], entry(base.entities, 'Text'))
            const rendered = serializer.Root(resolved, { indentation: '    ' }).__get_raw().join('\n')
            assert.doesNotMatch(rendered, /l entry|l id/)
            assert.deepEqual(plain(parse(rendered)), plain(authored))
        })

        const primitive = '| `data type` | `primitive type` ~'
        const record = reference => `| \`data type\` | \`structured data type\` ( fields: { 'value': ( type: ${reference} ) } )`
        const local = id => `| local ( entity: '${id}' )`
        const cyclic = id => `| \`local cyclic\` ( entity: '${id}' )`
        const external = (language, id) => `| external ( language: '${language}' entity: '${id}' )`
        const language = (dependencies, entities) =>
            `( version: "1" \`depends on\`: { ${dependencies} } entities: { ${entities} } )`
        const document = (languages, primary = 'Main') =>
            parse(`( languages: { ${languages} } \`primary language\`: '${primary}' )`)
        await t.test('local cyclic explicitly allows self and mutual references with identity-preserving handles', () => {
            const source = document(`'Main': ${language('', `
                'Self': ${record(cyclic('Self'))}
                'A': ${record(cyclic('B'))}
                'B': ${record(cyclic('A'))}
            `)}`)
            const resolved = resolve(source)
            const entities = entry(resolved.languages, 'Main').entities
            for (const [owner, target] of [['Self', 'Self'], ['A', 'B'], ['B', 'A']]) {
                const reference = entry(entry(entities, owner)[1][1].fields, 'value').type
                assert.equal(reference[0], 'local cyclic')
                assert.equal(reference[1].entity['l entry'].get_circular_dependent(), entry(entities, target))
            }
            assert.deepEqual(plain(parse(serializer.Root(resolved, { indentation: '    ' }).__get_raw().join('\n'))), plain(source))
            assert.throws(() => resolve(document(`'Main': ${language('', "'A': " + record(cyclic('Missing')))}`)),
                error => error.type === 'no such entry' && error.id === 'Missing')
        })
        await t.test('self and mutual language/entity dependencies fail explicitly', () => {
            const cases = [
                `'Main': ${language("'Main': 'Main'", '')}`,
                `'Main': ${language("'Base': 'Base'", '')} 'Base': ${language("'Main': 'Main'", '')}`,
                `'Main': ${language('', "'Self': " + record(local('Self')))}`,
                `'Main': ${language('', "'A': " + record(local('B')) + " 'B': " + record(local('A')))}`,
            ]
            for (const source of cases)
                assert.throws(() => resolve(document(source)), error => error.type === 'cycle detected', source)
        })
        await t.test('missing targets and undeclared or transitively declared languages fail explicitly', () => {
            const emptyMain = `'Main': ${language('', '')}`
            const cases = [
                [emptyMain, 'Missing', 'Missing'],
                [`'Main': ${language("'Missing': 'Missing'", '')}`, 'Main', 'Missing'],
                [`'Main': ${language('', "'A': " + record(local('Missing')))} `, 'Main', 'Missing'],
                [`'Main': ${language("'Base': 'Base'", "'A': " + record(external('Base', 'Missing')))}
                    'Base': ${language('', '')}`, 'Main', 'Missing'],
                [`'Main': ${language('', "'A': " + record(external('Base', 'Text')))}
                    'Base': ${language('', "'Text': " + primitive)}`, 'Main', 'Base'],
                [`'Main': ${language("'Middle': 'Middle'", "'A': " + record(external('Base', 'Text')))}
                    'Middle': ${language("'Base': 'Base'", '')}
                    'Base': ${language('', "'Text': " + primitive)}`, 'Main', 'Base'],
            ]
            for (const [source, primary, id] of cases)
                assert.throws(() => resolve(document(source, primary)), error =>
                    error.type === 'no such entry' && error.id === id, source)
        })
        await t.test('the full SysML fixture preserves the supplied language and resolves explicit local cycles', () => {
            const normalize = instanceTextNormalizer(Syntax_Lines(fixture('lioncore'), abort).join('\n'))
            const text = normalize(readFileSync(new URL('../temp/lioncore/sysml.lna', examples), 'utf8'))
            const value = parse(text)
            const sysml = entry(value.languages, 'sysml')
            const types = entry(value.languages, 'types')
            assert.equal(value['primary language'], 'sysml')
            assert.equal(entry(sysml['depends on'], 'types'), 'types')
            assert.deepEqual(types.entities.__get_raw().map(([id]) => id), ['Boolean', 'String', 'Integer', 'Real'])
            assert.ok(types.entities.__get_raw().every(([, entity]) => entity[0] === 'data type' && entity[1][0] === 'primitive type'))
            const original = JSON.parse(readFileSync(new URL('../packages/pareto-lionweb/data/SysML_lionweb_lionweb.json', base), 'utf8'))
            const nodes = new Map(original.nodes.map(node => [node.id, node]))
            const name = node => node.properties.find(property => property.property.key === 'LionCore-builtins-INamed-name').value
            const properties = node => Object.fromEntries(node.properties.map(property => [property.property.key, property.value]))
            const children = (node, key) => node.containments.find(containment => containment.containment.key === key).children
            const references = node => Object.fromEntries(node.references.map(reference =>
                [reference.reference.key, reference.targets.map(target => target.reference)]))
            const originalLanguage = original.nodes.find(node => node.classifier.key === 'Language')
            const entityIds = children(originalLanguage, 'Language-entities')
            assert.equal(sysml.version, properties(originalLanguage)['Language-version'])
            assert.deepEqual(sysml.entities.__get_raw().map(([id]) => id), entityIds.map(id => name(nodes.get(id))))
            const target = id => nodes.has(id)
                ? ['local', { entity: name(nodes.get(id)) }]
                : ['external', { language: 'types', entity: id.replace(/^types-/, '') }]
            let features = 0, literals = 0, selfReferences = 0, cyclicReferences = 0
            for (const id of entityIds) {
                const source = nodes.get(id)
                const converted = entry(sysml.entities, name(source))
                const refs = references(source)
                if (source.classifier.key === 'Enumeration') {
                    const ids = children(source, 'Enumeration-literals')
                    assert.deepEqual(plain(converted), plain(['data type', ['enumeration', {
                        literals: p.literal.dictionary(Object.fromEntries(ids.map(id => [name(nodes.get(id)), null]))),
                    }]]))
                    literals += ids.length
                    continue
                }
                assert.equal(converted[0], 'classifier')
                const classifier = converted[1]
                const featureIds = children(source, 'Classifier-features')
                assert.deepEqual(classifier.features.__get_raw().map(([id]) => id), featureIds.map(id => name(nodes.get(id))))
                for (const featureId of featureIds) {
                    const feature = nodes.get(featureId)
                    const props = properties(feature)
                    const convertedFeature = entry(classifier.features, name(feature))
                    const isProperty = feature.classifier.key === 'Property'
                    const referent = references(feature)[isProperty ? 'Property-type' : 'Link-type'][0]
                    assert.equal(convertedFeature.optional, props['Feature-optional'] === 'true')
                    assert.equal(convertedFeature.kind[0], isProperty ? 'property' : 'link')
                    const expected = target(referent)
                    if (convertedFeature.kind[1].type[0] === 'local cyclic') {
                        assert.equal(isProperty, false)
                        assert.equal(expected[0], 'local')
                        expected[0] = 'local cyclic'
                        cyclicReferences++
                    }
                    assert.deepEqual(convertedFeature.kind[1].type, expected)
                    if (!isProperty) {
                        assert.equal(convertedFeature.kind[1].multiple, props['Link-multiple'] === 'true')
                        assert.deepEqual(convertedFeature.kind[1].kind,
                            [feature.classifier.key === 'Containment' ? 'containment' : 'reference', null])
                    }
                    if (referent === id) selfReferences++
                    features++
                }
                if (source.classifier.key === 'Concept') {
                    const props = properties(source)
                    assert.equal(classifier.kind[0], 'concept')
                    assert.equal(classifier.kind[1].abstract, props['Concept-abstract'] === 'true')
                    assert.equal(classifier.kind[1].partition, props['Concept-partition'] === 'true')
                    assert.deepEqual(plain(classifier.kind[1].extends), plain(refs['Concept-extends'].length
                        ? p.literal.set(target(refs['Concept-extends'][0])) : p.literal.not_set()))
                    assert.deepEqual(classifier.kind[1].implements.__get_raw(), refs['Concept-implements'].map(target))
                } else {
                    assert.equal(classifier.kind[0], 'interface')
                    assert.deepEqual(classifier.kind[1].extends.__get_raw(), refs['Interface-extends'].map(target))
                }
            }
            assert.equal(entityIds.length, 222)
            assert.equal(features, 421)
            assert.equal(literals, 19)
            assert.equal(1 + entityIds.length + features + literals, original.nodes.length)
            assert.equal(selfReferences, 14)
            assert.equal(cyclicReferences, 248)
            const resolved = resolve(value)
            const resolvedSysml = entry(resolved.languages, 'sysml')
            const resolvedTypes = entry(resolved.languages, 'types')
            assert.equal(resolved['primary language']['l entry'], resolvedSysml)
            assert.equal(entry(resolvedSysml['depends on'], 'types')['l entry'], resolvedTypes)
            for (const [, classifier] of resolvedSysml.entities.__get_raw()) {
                if (classifier[0] !== 'classifier') continue
                for (const [, feature] of classifier[1].features.__get_raw()) {
                    const reference = feature.kind[1].type
                    const selected = reference[1].entity
                    const entities = reference[0] === 'external' ? resolvedTypes.entities : resolvedSysml.entities
                    assert.equal(reference[0] === 'local cyclic'
                        ? selected['l entry'].get_circular_dependent() : selected['l entry'],
                    entry(entities, selected['l id']))
                }
            }
            const rendered = serializer.Root(resolved, { indentation: '    ' }).__get_raw().join('\n')
            assert.deepEqual(plain(parse(rendered)), plain(value))
            const allAcyclic = parse(text.replaceAll(
                '| `local cyclic`', '| `local`'))
            assert.throws(() => resolve(allAcyclic), error =>
                error.type === 'cycle detected' && error.id === 'Subclassification')
        })
    } finally {
        rmSync(directory, { recursive: true })
    }
})

test('the native LionWeb serialization chunk schema round-trips SysML wire data without source ranges', async () => {
    const directory = mkdtempSync(join(tmpdir(), 'liana-next-lionweb-chunk-'))
    try {
        const source = input(fileURLToPath(new URL('projects/lioncore/sketch/serialization_chunk/liana.lna', base)))
        assert.equal(source[0], 'astn')
        const generated = pipeline(source)
        assert.deepEqual(placeholders(generated.pareto), [])
        assert.ok(!generated.pareto.schemas.__get_raw().some(([id]) => id === 'resolved'))
        write(generated.typescript, directory)
        assert.deepEqual(typecheck(directory), { status: 'passed' })
        compile(directory)
        const parser = await import(pathToFileURL(join(directory, 'dist/schemas/unresolved/refiners/list_of_characters.js')))
        const serializer = await import(pathToFileURL(join(directory, 'dist/schemas/unresolved/transformers/serialized_paragraph.js')))
        const original = JSON.parse(readFileSync(new URL('../packages/pareto-lionweb/data/SysML_lionweb_lionweb.json', base), 'utf8'))
        const optional = value => value === null ? p.literal.not_set() : p.literal.set(value)
        const node = value => ({
            ...value,
            parent: optional(value.parent),
            properties: p.literal.list(value.properties),
            containments: p.literal.list(value.containments.map(containment => ({
                ...containment, children: p.literal.list(containment.children),
            }))),
            references: p.literal.list(value.references.map(reference => ({
                ...reference, targets: p.literal.list(reference.targets.map(target => ({
                    ...target, reference: optional(target.reference),
                }))),
            }))),
            annotations: p.literal.list(value.annotations),
        })
        const sample = {
            id: 'sample', parent: null, classifier: original.nodes[0].classifier,
            properties: [{ property: original.nodes[0].properties[0].property, value: 'line one\nline two' }],
            containments: [], references: [{
                reference: original.nodes[0].references[0].reference,
                targets: [{ resolveInfo: 'not loaded', reference: null }],
            }], annotations: ['annotation-id'],
        }
        for (const nodes of [original.nodes, [sample]]) {
            const value = {
                serializationFormatVersion: original.serializationFormatVersion,
                languages: p.literal.list(original.languages),
                nodes: p.literal.list(nodes.map(node)),
            }
            const text = serializer.Root(value, { indentation: '    ' }).__get_raw().join('\n')
            const parsed = parser.Root(chars(text), abort, { 'tab size': 4 })
            assert.deepEqual(JSON.parse(JSON.stringify(parsed)), JSON.parse(JSON.stringify(value)))
            assert.ok(parsed.nodes.__get_raw().every(node => !Object.hasOwn(node, 'range')))
        }
    } finally {
        rmSync(directory, { recursive: true })
    }
})

test('the native schema-document API round-trips without derived-field placeholders', () => {
    const source = fixture('resolver')
    const serialized = authoringSerializer.Root(source, { indentation: '    ' }).__get_raw().join('\n')
    assert.doesNotMatch(serialized, /definition|resulting node|resulting type|resolved parameters|signature:/)
    assert.deepEqual(api.Root(chars(serialized), abort, { 'tab size': 4 }), source)
    const old = serialized.replace(/(root value resolver[^:]*:)/, 'signature: ~\n$1')
    assert.notEqual(old, serialized)
    assert.throws(() => api.Root(chars(old), abort, { 'tab size': 4 }))
    assert.deepEqual(Object.keys(entry(source[1].resolver.signatures.signatures, 'Root')), ['parameters'])
    assert.deepEqual(Object.keys(entry(source[1].resolver.types, 'Root')), ['root value resolver'])
})

test('Liana Next identity assertions compare selected nodes, not their contents', async () => {
    const source = `| liana (
        imports: {}
        globals: ( 'simple types': { 'Text': ( type: | text < | \`single line\` ~ | no ~ > ) } )
        types: {
            'Entry': ( 'root value': | group { 'label': < _ | simple 'Text' > } )
            'Entries': ( 'root value': | dictionary < | component < | internal 'Entry' _ > > )
            'Root': ( 'root value': | group {
                'entries': < _ | component < | internal 'Entries' _ > >
                'left': < _ | reference < < < | internal 'Entries' > < [] > > | selected < | acyclic ~ _ > > >
                'right': < _ | reference < < < | internal 'Entries' > < [] > > | selected < | acyclic ~ _ > > >
                'value': < _ | simple 'Text' >
            } )
        }
        resolver: (
            signatures: ( signatures: {
                'Entry': < | local < {} {} > >
                'Entries': < | local < {} {} > >
                'Root': < | local < {} {} > >
            } )
            types: {
                'Entry': < | group { 'label': < | simple ~ > } >
                'Entries': < | dictionary < | component < | internal 'Entry' _ {} > _ > >
                'Root': < | group {
                    'entries': < | component < | internal 'Entries' _ {} > >
                    'left': < | reference < | selected < < | acyclic | \`resolved dictionary\` < < | sibling 'entries' < [ | component ~ ] > > > > {} > > >
                    'right': < | reference < | selected < < | acyclic | \`resolved dictionary\` < < | sibling 'entries' < [ | component ~ ] > > > > {} > > >
                    'value': < | 'assert identity' (
                        left: < | sibling 'left' < [ | reference {} ] > >
                        right: < | sibling 'right' < [ | reference {} ] > >
                        resolver: | simple ~
                    ) >
                } >
            }
        )
        root: 'Root'
    )`
    const directory = mkdtempSync(join(tmpdir(), 'liana-next-identity-'))
    try {
        const schemaPath = join(directory, 'identity.liana.lna')
        symlinkSync(fileURLToPath(new URL('.liana/', examples)), join(directory, '.liana'), 'dir')
        writeFileSync(schemaPath, source)
        const generated = pipeline(input(schemaPath))
        assert.deepEqual(placeholders(generated.pareto), [])
        assert.equal(write(generated.typescript, directory).typescriptPlaceholders, 0)
        assert.deepEqual(typecheck(directory), { status: 'passed' })
        compile(directory)
        const resolver = await import(pathToFileURL(join(directory, 'dist/schemas/resolved/refiners/unresolved.js')))
        const instance = {
            entries: p.literal.dictionary({ first: { label: 'equal' }, second: { label: 'equal' } }),
            left: 'first', right: 'first', value: 'passed',
        }
        const output = resolver.Root(instance, abort, null, null)
        assert.equal(output.left['l entry'], output.right['l entry'])
        assert.equal(output.value, 'passed')
        assert.deepEqual(Object.keys(output).sort(), ['entries', 'left', 'right', 'value'])
        assert.throws(() => resolver.Root({ ...instance, right: 'second' }, abort, null, null), error =>
            error.type === 'identity mismatch' && error.path.__get_raw().join('/') === 'Root/value')
        assert.throws(() => resolver.Root({ ...instance, right: 'missing' }, abort, null, null), error =>
            error.type === 'no such entry' && error.id === 'missing')
    } finally {
        rmSync(directory, { recursive: true })
    }
})

test('the placeholder audit counts expression payloads, not dictionary option names', () => {
    assert.deepEqual(placeholders(p.literal.dictionary({ 'implement me': ['nothing', null] })), [])
    assert.deepEqual(placeholders(['implement me', { remark: 'unfinished' }]), [{ path: '', message: 'unfinished' }])
    const report = JSON.parse(readFileSync(new URL('projects/liana/sketch/temp/pipeline/audit.json', base), 'utf8'))
    assert.equal(report.examples, 54)
    assert.equal(report.emitted, 54)
    assert.equal(report.typechecksPassed, 54)
    assert.equal(report.typechecksFailed, 0)
    assert.equal(report.placeholderExpressions, 0)
    assert.equal(report.typescriptPlaceholderCalls, 0)
    assert.deepEqual(report.results.filter(result => result.placeholders.length).map(result => [result.name, result.placeholders.length]),
        [])
    assert.ok(!report.results.some(result => result.name === 'liana_next.liana.lna'))
    assert.ok(report.results.some(result => result.name === 'liana.liana.lna'))
    assert.ok(report.results.filter(result => result.branch === 'astn').every(result => result.status === 'emitted' && result.placeholders.length === 0))
    assert.deepEqual(report.results.filter(result => result.status === 'failed'), [])
})

test('Liana Next infers constraint metadata without declaring or parsing metadata fields', async () => {
    const model = fixture('resolver')[1]
    const dict = p.literal.dictionary
    const none = p.literal.not_set
    const state = options => ['state', {
        options: dict(Object.fromEntries(Object.entries(options).map(([id, value]) =>
            [id, { constraints: none(), description: none(), value }]))), results: none(),
    }]
    const stateResolver = options => ['state', { options: dict(options) }]
    const signature = entry(model.resolver.signatures.signatures, 'Root')
    const source = ['liana', {
        ...model,
        types: dict({
            Source: { 'root value': state({
                ready: ['group', dict({ label: { description: none(), value: ['simple', 'Text'] } })],
                other: ['nothing', null],
            }) },
            Root: { 'root value': state({ read: ['simple', 'Text'], skip: ['simple', 'Text'] }) },
        }),
        resolver: {
            signatures: { signatures: dict({
                Source: signature,
                Root: { ...signature, parameters: ['local', {
                    lookups: dict({}),
                    types: dict({ source: {
                        type: { location: ['internal', 'Source'] },
                        presence: ['required', null],
                    } }),
                }] },
            }) },
            types: dict({
                Source: { 'root value resolver': stateResolver({
                    ready: { constraints: dict({}), resolver: ['group', dict({ label: { resolver: ['simple', null] } })] },
                    other: { constraints: dict({}), resolver: ['nothing', null] },
                }) },
                Root: { 'root value resolver': stateResolver({
                    read: { constraints: dict({ ready: ['state', {
                        selection: {
                            start: ['parameter', 'source'],
                            tail: { path: p.literal.list([]) },
                        },
                        option: 'ready',
                    }] }), resolver: ['simple', null] },
                    skip: { constraints: dict({}), resolver: ['simple', null] },
                }) },
            }),
        },
    }]
    const rootSignature = entry(source[1].resolver.signatures.signatures, 'Root')
    const importedSource = ['liana', {
        ...source[1],
        imports: dict({ shared: source[1] }),
        types: dict({ Root: entry(source[1].types, 'Root') }),
        resolver: {
            signatures: { signatures: dict({ Root: {
                ...rootSignature,
                parameters: ['local', {
                    lookups: dict({}), types: dict({ source: {
                        type: { location: ['external', { import: 'shared', type: 'Source' }] },
                        presence: ['required', null],
                    } }),
                }],
            } }) },
            types: dict({ Root: entry(source[1].resolver.types, 'Root') }),
        },
    }]
    const bridge = {
        ...model,
        imports: dict({ deep: source[1] }),
        types: dict({ Source: { 'root value': ['component', {
            type: ['external', { import: 'deep', type: 'Source' }], results: none(),
        }] } }),
        root: 'Source',
        resolver: {
            signatures: { signatures: dict({ Source: signature }) },
            types: dict({ Source: { 'root value resolver': ['component', {
                location: ['external', {
                    'schema import': 'deep', 'resolver import': 'deep', signature: 'Source',
                }], arguments: none(), constraints: dict({}),
            }] } }),
        },
    }
    const rootResolver = entry(importedSource[1].resolver.types, 'Root')['root value resolver']
    const readOption = entry(rootResolver[1].options, 'read')
    const ready = entry(readOption.constraints, 'ready')
    const transitiveSource = ['liana', {
        ...importedSource[1], imports: dict({ shared: bridge }),
        resolver: {
            ...importedSource[1].resolver,
            types: dict({ Root: { 'root value resolver': ['state', {
                ...rootResolver[1],
                options: dict({
                    skip: entry(rootResolver[1].options, 'skip'),
                    read: { ...readOption, constraints: dict({ ready: ['state', {
                        ...ready[1], selection: {
                            ...ready[1].selection,
                            tail: { ...ready[1].selection.tail, path: p.literal.list([['component', null]]) },
                        },
                    }] }) },
                }),
            }] } }),
        },
    }]
    for (const schema of [source, importedSource, transitiveSource]) {
        const directory = mkdtempSync(join(tmpdir(), 'liana-next-metadata-'))
        try {
            const generated = pipeline(schema)
            assert.deepEqual(placeholders(generated.pareto), [])
            assert.equal(write(generated.typescript, directory).typescriptPlaceholders, 0)
            assert.deepEqual(typecheck(directory), { status: 'passed' })
            compile(directory)
            const parse = await import(pathToFileURL(join(directory, 'dist/schemas/unresolved/refiners/list_of_characters.js')))
            const resolve = await import(pathToFileURL(join(directory, 'dist/schemas/resolved/refiners/unresolved.js')))
            const serialize = await import(pathToFileURL(join(directory, 'dist/schemas/resolved/transformers/serialized_paragraph.js')))
            const authored = parse.Root(chars('| read "authored"'), abort, { 'tab size': 4 })
            assert.deepEqual(authored, ['read', 'authored'])
            const payload = { label: 'the node' }
            const resolved = resolve.Root(authored, abort, null, { source: ['ready', payload] })
            assert.deepEqual(resolved, ['read', { value: 'authored', meta: { ready: payload } }])
            assert.equal(resolved[1].meta.ready, payload)
            const serialized = serialize.Root(resolved, { indentation: '    ' }).__get_raw().join('\n')
            assert.doesNotMatch(serialized, /meta|the node|~/)
            assert.deepEqual(parse.Root(chars(serialized), abort, { 'tab size': 4 }), authored)
            assert.deepEqual(resolve.Root(['skip', 'ordinary'], abort, null, { source: ['other', null] }), ['skip', 'ordinary'])
            assert.throws(() => resolve.Root(authored, abort, null, { source: ['other', null] }),
                error => error.type === 'unexpected state option' && error.id === 'ready')
        } finally {
            rmSync(directory, { recursive: true })
        }
    }
})

test('group selection constraints infer metadata types, preserve dependencies and identity, and serialize only data', async () => {
    const dict = p.literal.dictionary
    const base = fixture('resolver')[1]
    const selection = (kind, name, path = []) => ({ start: [kind, name], tail: { path: p.literal.list(path) } })
    const constraints = {
        alias: selection('metadata', 'node'),
        node: selection('sibling', 'seed', [['component', null]]),
    }
    const properties = dict({
        seed: { resolver: ['component', { location: ['internal', 'Source'], arguments: p.literal.not_set(), constraints: dict({}) }] },
        meta: { resolver: ['simple', null] },
    })
    const signature = entry(base.resolver.signatures.signatures, 'Root')
    const withConstraints = results => ['liana', {
        ...base,
        types: dict({
            Source: { 'root value': ['group', dict({ label: { description: p.literal.not_set(), value: ['simple', 'Text'] } })] },
            Root: { 'root value': ['group', dict({
                seed: { description: p.literal.not_set(), value: ['component', { type: ['internal', 'Source'], results: p.literal.not_set() }] },
                meta: { description: p.literal.not_set(), value: ['simple', 'Text'] },
            })] },
        }),
        resolver: {
            signatures: { ...base.resolver.signatures, signatures: dict({ Source: signature, Root: signature }) },
            types: dict({
                Source: { 'root value resolver': ['group', dict({ label: { resolver: ['simple', null] } })] },
                Root: { 'root value resolver': ['with constraints', { constraints: dict(results), resolver: properties }] },
            }),
        },
    }]
    const source = withConstraints(constraints)
    const serializedSchema = authoringSerializer.Root(source, { indentation: '    ' }).__get_raw().join('\n')
    assert.deepEqual(api.Root(chars(serializedSchema), abort, { 'tab size': 4 }), source)
    const directory = mkdtempSync(join(tmpdir(), 'liana-next-group-metadata-'))
    try {
        const generated = pipeline(source)
        assert.deepEqual(placeholders(generated.pareto), [])
        assert.equal(write(generated.typescript, directory).typescriptPlaceholders, 0)
        assert.deepEqual(typecheck(directory), { status: 'passed' })
        compile(directory)
        const parse = await import(pathToFileURL(join(directory, 'dist/schemas/unresolved/refiners/list_of_characters.js')))
        const resolve = await import(pathToFileURL(join(directory, 'dist/schemas/resolved/refiners/unresolved.js')))
        const serialize = await import(pathToFileURL(join(directory, 'dist/schemas/resolved/transformers/serialized_paragraph.js')))
        const authored = parse.Root(chars('( seed: ( label: "node" ) meta: "authored" )'), abort, { 'tab size': 4 })
        assert.deepEqual(authored, { seed: { label: 'node' }, meta: 'authored' })
        const output = resolve.Root(authored, abort, null, null)
        assert.deepEqual(output, { value: authored, meta: { alias: authored.seed, node: authored.seed } })
        assert.equal(output.meta.node, output.value.seed)
        assert.equal(output.meta.alias, output.meta.node)
        const serialized = serialize.Root(output, { indentation: '    ' }).__get_raw().join('\n')
        assert.doesNotMatch(serialized, /alias|node:/)
        assert.deepEqual(parse.Root(chars(serialized), abort, { 'tab size': 4 }), authored)
        assert.throws(() => parse.Root(chars('( seed: ( label: "node" ) meta: "authored" node: ~ )'), abort, { 'tab size': 4 }))
    } finally {
        rmSync(directory, { recursive: true })
    }
    assert.throws(() => pipeline(withConstraints({ alias: selection('metadata', 'absent') })), /absent/)
    assert.throws(() => pipeline(withConstraints({ alias: selection('metadata', 'node'), node: selection('metadata', 'alias') })),
        /cyclic metadata constraints/)
    assert.throws(() => pipeline(withConstraints({ seed: constraints.node })), /constraint conflicts with authored property seed/)
})

test('all eleven instance computations are constraints, with no native derived-reference alternative', () => {
    const schema = fixture('liana')[1]
    for (const name of ['Value', 'Resolver Value']) {
        const reference = entry(entry(schema.types, name)['root value'][1], 'reference').value
        const alternatives = entry(reference[1], 'type').value[1].__get_raw().map(([id]) => id)
        assert.deepEqual(alternatives, ['selected'])
    }
    for (const [name, expected] of [['boekhouding', 6], ['json_schema_light', 1], ['programming_languages--pareto_next', 4]]) {
        let count = 0
        const visit = value => {
            if (value === null || typeof value !== 'object') return
            if (Array.isArray(value)) {
                if (value[0] === 'with constraints') count += value[1].constraints.__get_raw().length
                if (value[0] === 'reference' && value[1]?.type) assert.notEqual(value[1].type[0], 'derived')
                value.forEach(visit)
            } else if (value.__get_raw) visit(value.__get_raw())
            else Object.values(value).forEach(visit)
        }
        visit(fixture(name))
        assert.equal(count, expected, name)
    }
})

test('optional component results forward present and absent values without schema-specific handling', async () => {
    const dict = p.literal.dictionary
    const none = p.literal.not_set
    const base = fixture('resolver')[1]
    const plain = entry(base.resolver.signatures.signatures, 'Root')
    const signature = { parameters: ['local', {
        types: dict({ argument: { type: { location: ['internal', 'Source'] }, presence: ['optional', null] } }),
        lookups: dict({}),
    }] }
    const component = name => ['component', { type: ['internal', name], results: none() }]
    const property = value => ({ description: none(), value })
    const resolveComponent = name => ['component', {
        location: ['internal', name], arguments: p.literal.set({ types: p.literal.set(dict({})), lookups: p.literal.set(dict({})) }),
        constraints: dict({}),
    }]
    const source = ['liana', {
        ...base,
        types: dict({
            Source: { 'root value': ['simple', 'Text'] },
            Receiver: { 'root value': ['optional', ['simple', 'Text']] },
            Root: { 'root value': ['group', dict({
                seed: property(['optional', component('Source')]), receiver: property(component('Receiver')),
            })] },
        }),
        resolver: {
            signatures: { signatures: dict({ Source: plain, Receiver: signature, Root: plain }) },
            types: dict({
                Source: { 'root value resolver': ['simple', null] },
                Receiver: { 'root value resolver': ['optional', {
                    constraints: dict({ argument: ['assert is set', ['parameter', 'argument']] }),
                    resolver: ['simple', null],
                }] },
                Root: { 'root value resolver': ['group', dict({
                    seed: { resolver: ['optional', { constraints: dict({}), resolver: resolveComponent('Source') }] },
                    receiver: { resolver: ['component', {
                        ...resolveComponent('Receiver')[1],
                        arguments: p.literal.set({
                            types: p.literal.set(dict({ argument: ['optional', ['selection', ['result', ['optional value', {
                                property: 'seed', result: { location: ['internal', 'Source'] },
                            }]]]] })),
                            lookups: p.literal.set(dict({})),
                        }),
                    }] },
                })] },
            }),
        },
    }]
    const directory = mkdtempSync(join(tmpdir(), 'liana-next-optional-result-'))
    try {
        const generated = pipeline(source)
        assert.deepEqual(placeholders(generated.pareto), [])
        write(generated.typescript, directory)
        assert.deepEqual(typecheck(directory), { status: 'passed' })
        compile(directory)
        const resolve = await import(pathToFileURL(join(directory, 'dist/schemas/resolved/refiners/unresolved.js')))
        for (const seed of [none(), p.literal.set('node')]) {
            const authored = { seed, receiver: none() }
            const output = resolve.Root(authored, abort, null, null)
            assert.deepEqual(output.seed.__get_raw(), seed.__get_raw())
            assert.equal(output.receiver.__get_raw(), null)
        }
        const present = resolve.Root({ seed: p.literal.set('node'), receiver: p.literal.set('authored') }, abort, null, null)
        assert.deepEqual(present.receiver.__get_raw(), [{ value: 'authored', meta: { argument: 'node' } }])
        assert.throws(() => resolve.Root({ seed: none(), receiver: p.literal.set('authored') }, abort, null, null),
            error => error.type === 'optional value not set' && error.id === 'argument')
    } finally {
        rmSync(directory, { recursive: true })
    }
})

test('accounting migrations retain their registry structure and explicit resolver corrections', () => {
    for (const name of ['boekhouding', 'boekhouding_oude_model']) {
        const source = readFileSync(new URL('../liana_registry/liana/' + name + '.liana.lna', base), 'utf8')
        const expected = readFileSync(new URL(name + '.liana.lna', examples), 'utf8')
        assert.equal(sealedSchemaText(convert(source, { correctBoekhouding: name === 'boekhouding' })),
            sealedSchemaText(expected))
        const next = fixture(name)
        assert.equal(next[0], name === 'boekhouding' ? 'liana' : 'astn')
        const generated = pipeline(next)
        assert.deepEqual(placeholders(generated.pareto), [])
    }
})

test('generated Boekhouding follows the proven bank-mutation and Resultaat lookup behavior', async () => {
    const directory = mkdtempSync(join(tmpdir(), 'liana-next-boekhouding-'))
    try {
        const generated = pipeline(fixture('boekhouding'))
        assert.equal(write(generated.typescript, directory).typescriptPlaceholders, 0)
        assert.deepEqual(typecheck(directory), { status: 'passed' })
        compile(directory)
        const resolver = await import(pathToFileURL(join(directory, 'dist/schemas/resolved/refiners/unresolved.js')))
        const parser = await import(pathToFileURL(join(directory, 'dist/schemas/unresolved/refiners/list_of_characters.js')))
        const serializer = await import(pathToFileURL(join(directory, 'dist/schemas/resolved/transformers/serialized_paragraph.js')))
        const dict = p.literal.dictionary
        const stamp = { Bedrag: 123, Datum: 20454 }
        const bank = { Mutaties: dict({ payment: stamp }) }
        const account = { marker: 'Resultaat account' }
        const informal = { marker: 'Informal account' }
        const settlement = { marker: 'Settlement account' }
        const balanceAccount = { marker: 'Balance account' }
        const resolvedAccounts = resolver.Grootboekrekeningen({ Balans: dict({ balance: {} }), Resultaat: dict({ expense: {} }) },
            abort, null, { Beheer: { Grootboekrekeningen: { Balans: dict({ balance: balanceAccount }), Resultaat: dict({ expense: account }) } } })
        assert.equal(entry(resolvedAccounts.Balans, 'balance').meta.Stam, balanceAccount)
        assert.equal(entry(resolvedAccounts.Resultaat, 'expense').meta.Stam, account)
        const year = {
            Balans: {
                Verrekenposten: dict({ settlement }),
                Bankrekeningen: dict({ bank }),
                'Overige balans items': dict({ item: { marker: 'Balance item' } }),
                'Informele rekeningen': dict({ informal }),
            },
        }
        const parameters = {
            Jaarbeheer: year,
            Grootboekrekeningen: { Balans: dict({}), Resultaat: dict({ expense: account }) },
            Handelstransacties: { Inkopen: dict({}), Verkopen: dict({}) },
        }
        const processing = id => dict({ [id]: {
            type: ['Balans', ['Informele rekening', { 'Informele rekening': 'informal' }]],
        } })
        const source = {
            Verrekenposten: dict({ settlement: { Mutaties: dict({}) } }),
            Bankrekeningen: dict({ bank: { 'Mutatie Verwerkingen': processing('payment') } }),
            'Overige Balans Items': dict({ item: {
                'Memoriaal Boekingen': dict({ booking: {
                    Bedrag: 123, Datum: 20454, Omschrijving: 'Expense', Grootboekrekening: 'expense',
                } }),
            } }),
        }
        const output = resolver.Mutaties(source, abort, { Jaren: lookup.acyclic.from_resolved_dictionary(dict({})) }, parameters)
        const resolvedBank = entry(output.Bankrekeningen, 'bank')
        assert.equal(resolvedBank.meta.Stam, bank)
        assert.equal(entry(resolvedBank.value['Mutatie Verwerkingen'], 'payment').meta.Stam, stamp)
        assert.equal(entry(output.Verrekenposten, 'settlement').meta.Stam, settlement)
        const resolvedItem = entry(output['Overige Balans Items'], 'item')
        assert.equal(resolvedItem.meta.Stam, entry(year.Balans['Overige balans items'], 'item'))
        assert.equal(entry(resolvedItem.value['Memoriaal Boekingen'], 'booking').Grootboekrekening['l entry'], account)
        for (const [type, resolved, authored] of [
            ['Mutaties', output, source],
            ['Grootboekrekeningen', resolvedAccounts, { Balans: dict({ balance: {} }), Resultaat: dict({ expense: {} }) }],
        ]) {
            const serialized = serializer[type](resolved, { indentation: '    ' }).__get_raw().join('\n')
            assert.doesNotMatch(serialized, /Stam/)
            let roundTrip
            assert.doesNotThrow(() => { roundTrip = parser[type](chars(serialized), abort, { 'tab size': 4 }) },
                type + ' round-trip:\n' + serialized)
            assert.deepEqual(JSON.parse(JSON.stringify(roundTrip)), JSON.parse(JSON.stringify(authored)))
        }
        assert.throws(() => resolver.Mutaties({
            ...source, Bankrekeningen: dict({ bank: { 'Mutatie Verwerkingen': processing('absent') } }),
        }, abort, { Jaren: lookup.acyclic.from_resolved_dictionary(dict({})) }, parameters), error =>
            error.type === 'no benchmark entry' && error.id === 'absent')
        for (const [invalid, type, id] of [
            [{ ...source, Bankrekeningen: dict({ missingBank: source.Bankrekeningen.__get_raw()[0][1] }) },
                'no benchmark entry', 'missingBank'],
            [{ ...source, Verrekenposten: dict({ missingSettlement: { Mutaties: dict({}) } }) },
                'no benchmark entry', 'missingSettlement'],
            [{ ...source, 'Overige Balans Items': dict({ missingItem: { 'Memoriaal Boekingen': dict({}) } }) },
                'no benchmark entry', 'missingItem'],
            [{ ...source, Bankrekeningen: dict({ bank: { 'Mutatie Verwerkingen': dict({ payment: {
                type: ['Balans', ['Informele rekening', { 'Informele rekening': 'missingInformal' }]],
            } }) } }) }, 'no such entry', 'missingInformal'],
            [{ ...source, 'Overige Balans Items': dict({ item: { 'Memoriaal Boekingen': dict({ booking: {
                Bedrag: 123, Datum: 20454, Omschrijving: 'Expense', Grootboekrekening: 'balance',
            } }) } }) }, 'no such entry', 'balance'],
        ]) {
            assert.throws(() => resolver.Mutaties(invalid, abort,
                { Jaren: lookup.acyclic.from_resolved_dictionary(dict({})) }, parameters),
            error => error.type === type && error.id === id, id)
        }
        const prepared = JSON.parse(execFileSync(process.execPath, [
            fileURLToPath(new URL('tools/liana/prepare_schema.mjs', base)),
            fileURLToPath(new URL('boekhouding.liana.lna', examples)),
        ], { encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 }))
        mkdirSync(join(directory, '.liana'))
        writeFileSync(join(directory, '.liana/schema.slna'), prepared.syntax)
        writeFileSync(join(directory, 'years.lna'), boekhoudingYears)
        const sealed = execFileSync(process.execPath, [
            fileURLToPath(new URL('tools/old_style/liana_authoring/dist/bin/seal.js', base)), join(directory, 'years.lna'),
        ], { encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 })
        const authored = parser.Root(chars(sealed), abort, { 'tab size': 4 })
        const root = resolver.Root(authored, abort, null, null)
        const first = entry(root.Jaren, '2024')
        const second = entry(root.Jaren, '2025')
        assert.equal(second['Eerste boekjaar'][1]['Vorig boekjaar']['l entry'], first)
        for (const [id, property, group] of [
            ['zakelijk', 'Rekening', 'Bankrekeningen'],
            ['prive', 'Rekening', 'Informele rekeningen'],
            ['voorraad', 'Balans item', 'Overige balans items'],
        ]) {
            const current = entry(second.Jaarbeheer.Balans[group], id)
            assert.equal(current.Nieuw[1].value[property]['l entry'], entry(first.Jaarbeheer.Balans[group], id))
        }
        const customer = entry(root.Beheer.Klanten, 'klant')
        const sale = entry(second.Handelstransacties.Verkopen, 'projectfactuur')
        assert.equal(sale.Debiteur['l entry'], customer)
        const project = entry(customer.Projecten, 'project')
        const quote = entry(project.Offertes, 'offerte')
        assert.equal(sale.Contracttype[1].Project['l entry'], project)
        assert.equal(sale.Contracttype[1].Offerte['l entry'], quote)
        assert.equal(entry(sale.Regels, 'standaard').Contracttype[1].value.Opbrengst['l entry'],
            entry(quote.Opbrengsten, 'mijlpaal'))
        const licenseSale = entry(second.Handelstransacties.Verkopen, 'licentiefactuur')
        const license = entry(customer.Licentieovereenkomsten, 'licentie')
        assert.equal(licenseSale.Contracttype[1].Overeenkomst['l entry'], license)
        assert.equal(entry(licenseSale.Regels, 'periode').Contracttype[1].value.Periode['l entry'],
            entry(license.Periodes, 'periode'))
        const mutations = entry(second.Mutaties.Bankrekeningen, 'zakelijk').value['Mutatie Verwerkingen']
        assert.equal(entry(mutations, 'betaling').value.type[1].type[1]['l entry'],
            entry(second.Handelstransacties.Inkopen, 'factuur'))
        const priorMutation = entry(mutations, 'vorig').value.type[1]
        assert.equal(priorMutation.Jaar.__get_raw()[0]['l entry'], first)
        assert.equal(priorMutation.type[1]['l entry'],
            entry(first.Handelstransacties.Verkopen, 'licentiefactuur'))
        for (const [option, id, selectTarget] of [
            ['Inkoop', 'factuur', year => entry(year.Handelstransacties.Inkopen, 'historische factuur')],
            ['Verkoop', 'licentiefactuur', year => entry(year.Handelstransacties.Verkopen, 'historische licentiefactuur')],
            ['BTW-periode', 'kwartaal', year => entry(year.Jaarbeheer.Resultaat['BTW periodes'], 'historische kwartaal')],
        ]) {
            const before = boekhoudingYears.indexOf("'2024':")
            const after = boekhoudingYears.indexOf("'2025':")
            assert.ok(before >= 0 && after > before)
            const firstYear = boekhoudingYears.slice(before, after).replaceAll("'" + id + "'", "'historische " + id + "'")
            const text = boekhoudingYears.slice(0, before) + firstYear + boekhoudingYears.slice(after)
                .replace("* '2024' | `Verkoop` 'licentiefactuur'", "* '2024' | `" + option + "` 'historische " + id + "'")
            writeFileSync(join(directory, 'years.lna'), text)
            const sealedCase = execFileSync(process.execPath, [
                fileURLToPath(new URL('tools/old_style/liana_authoring/dist/bin/seal.js', base)), join(directory, 'years.lna'),
            ], { encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 })
            const output = resolver.Root(parser.Root(chars(sealedCase), abort, { 'tab size': 4 }), abort, null, null)
            const current = entry(output.Jaren, '2025')
            const previous = entry(output.Jaren, '2024')
            const result = entry(entry(current.Mutaties.Bankrekeningen, 'zakelijk').value['Mutatie Verwerkingen'], 'vorig').value.type[1]
            assert.equal(result.type[1]['l entry'], selectTarget(previous), option + ' must select prior-year-only target')
        }
        const roundTrip = serializer.Root(root, { indentation: '    ' }).__get_raw().join('\n')
        assert.doesNotMatch(roundTrip, /`Stam`|`meta`|`l entry`/)
        assert.deepEqual(JSON.parse(JSON.stringify(parser.Root(chars(roundTrip), abort, { 'tab size': 4 }))),
            JSON.parse(JSON.stringify(authored)))
    } finally {
        rmSync(directory, { recursive: true })
    }
})

test('the formerly blocked schemas emit explicit lookup conversion and forwarding', () => {
    const optionalLookups = expression => {
        assert.equal(expression[0], 'change context')
        const conversion = expression[1].callback
        assert.equal(conversion[0], 'convert')
        assert.equal(conversion[1].type[0], 'optional')
        const body = conversion[1].type[1][1]['on set']
        assert.equal(body[0], 'with bindings')
        const component = body[1].result[1].type
        assert.equal(component[0], 'component')
        assert.equal(component[1][0], 'transform')
        const arguments_ = component[1][1].arguments
        assert.equal(arguments_[0], 'resolver')
        assert.equal(arguments_[1].lookups[0], 'initialize')
        return arguments_[1].lookups[1]
    }
    const definitions = entry(pipeline(fixture('json_schema_light')).pareto.schemas, 'resolved')
    const resolver = entry(definitions.refiners, 'unresolved')
    const document = entry(resolver.implementations, 'Document').expression
    const root = entry(document[1], 'root value')
    const lookups = optionalLookups(root)
    assert.equal(entry(lookups, 'values')[0], 'cyclic resolved dictionary')
    const namespaces = entry(lookups, 'namespaces')
    assert.equal(namespaces[0], 'push stack')
    assert.deepEqual(namespaces[1].stack, ['parameter', 'namespaces'])
    assert.equal(namespaces[1].item[0], 'resolved dictionary')

    const pareto = entry(pipeline(fixture('programming_languages--pareto_next')).pareto.schemas, 'resolved')
    const transformer = entry(entry(pareto.refiners, 'unresolved').implementations, 'Transformer Root').expression
    const parameters = entry(transformer[1], 'parameters schema')
    assert.deepEqual(entry(optionalLookups(parameters), 'packages'), ['parameter', 'packages'])
})
