import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { createRequire } from 'node:module'
import { mkdtempSync, readFileSync, rmSync, writeFileSync, existsSync, symlinkSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import test from 'node:test'
import { input, pipeline, placeholders, write, typecheck } from '../../../../newstyle_projects/projects/liana_next/sketch/temp/pipeline.mjs'
import * as api from '../../../../newstyle_projects/projects/liana_next/sketch/transformers/pareto_next_sketch/typescript/dist/modules/source.liana.generated/schemas/unresolved/refiners/list_of_characters.js'
import * as authoringSerializer from '../../../../newstyle_projects/projects/liana_next/sketch/transformers/pareto_next_sketch/typescript/dist/modules/source.liana.generated/schemas/unresolved/transformers/serialized_paragraph.js'
import { convert } from '../../../../newstyle_projects/projects/liana_next/sketch/temp/convert_registry.mjs'

const base = new URL('../../../../newstyle_projects/', import.meta.url)
const examples = new URL('projects/liana_next/sketch/examples/', base)
const require = createRequire(new URL('projects/liana_next/sketch/transformers/pareto_next_sketch/typescript/package.json', base))
const p = await import(require.resolve('pareto-core/transformer'))
const lookup = await import(require.resolve('pareto-core/refiner/specials/lookup'))
const abort = error => { throw error }
const chars = source => p.literal.list(Array.from(source, c => c.codePointAt(0)))
const entry = (dictionary, name) => p.from.dictionary(dictionary).get_possible_entry(name, value => value, () => assert.fail(name))
const fixture = name => input(fileURLToPath(new URL(name + '.liana_next.lna', examples)))
const compile = directory => {
    const configuration = join(directory, 'tsconfig.json')
    const config = JSON.parse(readFileSync(configuration, 'utf8'))
    config.compilerOptions.noEmit = false
    config.compilerOptions.outDir = 'dist'
    writeFileSync(configuration, JSON.stringify(config))
    execFileSync(process.execPath, [fileURLToPath(new URL('tools/typescript.cjs', base)), '-p', directory], { stdio: 'pipe' })
}

test('the Liana Next API is generated by the new pipeline, with no semantic resolver for ASTN', () => {
    const generated = pipeline(fixture('liana_next'))
    assert.deepEqual(placeholders(generated.pareto), [])
    const apiPath = fileURLToPath(new URL('projects/liana_next/sketch/transformers/pareto_next_sketch/typescript/src/modules/source.liana.generated/', base))
    assert.ok(existsSync(join(apiPath, 'schemas/unresolved/schema.ts')))
    assert.equal(existsSync(join(apiPath, 'schemas/resolved')), false)
    assert.deepEqual(api.Root(chars("| astn ( imports: {} globals: ( 'simple types': {} ) types: { 'Root': ( 'root value': | nothing ~ ) } root: 'Root' )"),
        abort, { 'tab size': 4 })[0], 'astn')
})

test('ASTN API round-trips simple reference/id syntax and resolves inline imports without lookup placeholders', async () => {
    for (const name of ['identifiers', 'imports', 'data_formats--json']) {
        const directory = mkdtempSync(join(tmpdir(), 'liana-next-pipeline-'))
        try {
            const generated = pipeline(fixture(name))
            assert.deepEqual(placeholders(generated.pareto), [], name)
            assert.equal(entry(generated.pareto.schemas, 'unresolved').refiners.__get_raw().length, 2)
            assert.ok(!generated.pareto.schemas.__get_raw().some(([id]) => id === 'resolved'))
            const output = write(generated.typescript, directory)
            assert.equal(output.typescriptPlaceholders, 0)
            assert.deepEqual(typecheck(directory), { status: 'passed' })
            compile(directory)
            const parser = await import(pathToFileURL(join(directory, 'dist/schemas/unresolved/refiners/list_of_characters.js')))
            const serializer = await import(pathToFileURL(join(directory, 'dist/schemas/unresolved/transformers/serialized_paragraph.js')))
            if (name === 'identifiers') {
                const source = "( name: 'alice' target: 'bob' description: \"hello\" )"
                const value = parser.Root(chars(source), abort, { 'tab size': 4 })
                assert.deepEqual(value, { name: 'alice', target: 'bob', description: 'hello' })
                const rendered = serializer.Root(value, { indentation: '    ' }).__get_raw().join('\n')
                assert.match(rendered, /'alice'/)
                assert.match(rendered, /'bob'/)
                assert.match(rendered, /"hello"/)
                assert.deepEqual(parser.Root(chars(rendered), abort, { 'tab size': 4 }), value)
            } else if (name === 'imports') {
                assert.equal(parser.Root(chars("'alice'"), abort, { 'tab size': 4 }), 'alice')
                assert.equal(serializer.Root('alice', { indentation: '    ' }).__get_raw().join('\n'), "'alice'")
            } else {
                const value = parser.Root(chars('| string "hello"'), abort, { 'tab size': 4 })
                assert.deepEqual(value, ['string', 'hello'])
                assert.deepEqual(parser.Root(chars(serializer.Root(value, { indentation: '    ' }).__get_raw().join('\n')), abort, { 'tab size': 4 }), value)
            }
        } finally {
            rmSync(directory, { recursive: true })
        }
    }
})

test('semantic API exposes parsing and the declared resolver separately', async () => {
    const directory = mkdtempSync(join(tmpdir(), 'liana-next-semantic-'))
    try {
        const generated = pipeline(fixture('resolver'))
        const resolved = entry(generated.pareto.schemas, 'resolved')
        assert.ok(resolved.refiners.__get_raw().some(([id]) => id === 'unresolved'))
        assert.ok(!resolved.refiners.__get_raw().some(([id]) => id === 'list of characters'))
        write(generated.typescript, directory)
        assert.deepEqual(typecheck(directory), { status: 'passed' })
        compile(directory)
        const parser = await import(pathToFileURL(join(directory, 'dist/schemas/unresolved/refiners/list_of_characters.js')))
        const resolver = await import(pathToFileURL(join(directory, 'dist/schemas/resolved/refiners/unresolved.js')))
        assert.equal(resolver.Root(parser.Root(chars('"hello"'), abort, { 'tab size': 4 }), abort, null, null), 'hello')
    } finally {
        rmSync(directory, { recursive: true })
    }
})

test('the native schema-document API round-trips without derived-field placeholders', () => {
    const source = fixture('resolver')
    const serialized = authoringSerializer.Root(source, { indentation: '    ' }).__get_raw().join('\n')
    assert.doesNotMatch(serialized, /definition|resulting node|resulting type|resolved parameters|signature:/)
    assert.deepEqual(api.Root(chars(serialized), abort, { 'tab size': 4 }), source)
    const old = serialized.replace(/(root value resolver[^:]*:)/, 'signature: ~\n$1')
    assert.notEqual(old, serialized)
    assert.throws(() => api.Root(chars(old), abort, { 'tab size': 4 }))
    assert.deepEqual(Object.keys(entry(source[1].resolver.signatures.signatures, 'Root')), ['parameters'])
    assert.deepEqual(Object.keys(entry(source[1].resolver.types, 'Root')), ['root value resolver'])
})

test('Liana Next identity assertions compare selected nodes, not their contents', async () => {
    const source = `| liana (
        imports: {}
        globals: ( 'simple types': { 'Text': ( type: | text < | \`single line\` ~ | no ~ > ) } )
        types: {
            'Entry': ( 'root value': | group { 'label': < _ | simple 'Text' > } )
            'Entries': ( 'root value': | dictionary < | component < | internal 'Entry' _ > > )
            'Root': ( 'root value': | group {
                'entries': < _ | component < | internal 'Entries' _ > >
                'left': < _ | reference < < < | internal 'Entries' > < [] > > | selected < | acyclic ~ _ > > >
                'right': < _ | reference < < < | internal 'Entries' > < [] > > | selected < | acyclic ~ _ > > >
                'value': < _ | simple 'Text' >
            } )
        }
        resolver: (
            signatures: ( signatures: {
                'Entry': < | local < {} {} > >
                'Entries': < | local < {} {} > >
                'Root': < | local < {} {} > >
            } )
            types: {
                'Entry': < | group { 'label': < | simple ~ > } >
                'Entries': < | dictionary < | component < | internal 'Entry' _ {} > _ > >
                'Root': < | group {
                    'entries': < | component < | internal 'Entries' _ {} > >
                    'left': < | reference < | selected < < | acyclic | \`resolved dictionary\` < < | sibling 'entries' < [ | component ~ ] > > > > {} > > >
                    'right': < | reference < | selected < < | acyclic | \`resolved dictionary\` < < | sibling 'entries' < [ | component ~ ] > > > > {} > > >
                    'value': < | 'assert identity' (
                        left: < | sibling 'left' < [ | reference {} ] > >
                        right: < | sibling 'right' < [ | reference {} ] > >
                        resolver: | simple ~
                    ) >
                } >
            }
        )
        root: 'Root'
    )`
    const directory = mkdtempSync(join(tmpdir(), 'liana-next-identity-'))
    try {
        const schemaPath = join(directory, 'identity.liana_next.lna')
        symlinkSync(fileURLToPath(new URL('.liana/', examples)), join(directory, '.liana'), 'dir')
        writeFileSync(schemaPath, source)
        const generated = pipeline(input(schemaPath))
        assert.deepEqual(placeholders(generated.pareto), [])
        assert.equal(write(generated.typescript, directory).typescriptPlaceholders, 0)
        assert.deepEqual(typecheck(directory), { status: 'passed' })
        compile(directory)
        const resolver = await import(pathToFileURL(join(directory, 'dist/schemas/resolved/refiners/unresolved.js')))
        const instance = {
            entries: p.literal.dictionary({ first: { label: 'equal' }, second: { label: 'equal' } }),
            left: 'first', right: 'first', value: 'passed',
        }
        const output = resolver.Root(instance, abort, null, null)
        assert.equal(output.left['l entry'], output.right['l entry'])
        assert.equal(output.value, 'passed')
        assert.deepEqual(Object.keys(output).sort(), ['entries', 'left', 'right', 'value'])
        assert.throws(() => resolver.Root({ ...instance, right: 'second' }, abort, null, null), error =>
            error.type === 'identity mismatch' && error.path.__get_raw().join('/') === 'Root/value')
        assert.throws(() => resolver.Root({ ...instance, right: 'missing' }, abort, null, null), error =>
            error.type === 'no such entry' && error.id === 'missing')
    } finally {
        rmSync(directory, { recursive: true })
    }
})

test('the placeholder audit counts expression payloads, not dictionary option names', () => {
    assert.deepEqual(placeholders(p.literal.dictionary({ 'implement me': ['nothing', null] })), [])
    assert.deepEqual(placeholders(['implement me', { remark: 'unfinished' }]), [{ path: '', message: 'unfinished' }])
    const report = JSON.parse(readFileSync(new URL('projects/liana_next/sketch/temp/pipeline/audit.json', base), 'utf8'))
    assert.equal(report.examples, 54)
    assert.equal(report.emitted, 54)
    assert.equal(report.typechecksPassed, 54)
    assert.equal(report.typechecksFailed, 0)
    assert.equal(report.placeholderExpressions, 6)
    assert.equal(report.typescriptPlaceholderCalls, 6)
    assert.deepEqual(report.results.filter(result => result.placeholders.length).map(result => [result.name, result.placeholders.length]),
        [['json_schema_light.liana_next.lna', 2],
            ['programming_languages--pareto_next.liana_next.lna', 3], ['sql_query.liana_next.lna', 1]])
    assert.ok(!report.results.some(result => result.name === 'liana.liana_next.lna'))
    assert.ok(report.results.some(result => result.name === 'liana_next.liana_next.lna'))
    assert.ok(report.results.filter(result => result.branch === 'astn').every(result => result.status === 'emitted' && result.placeholders.length === 0))
    assert.deepEqual(report.results.filter(result => result.status === 'failed'), [])
})

test('Liana Next infers constraint metadata without declaring or parsing metadata fields', async () => {
    const model = fixture('resolver')[1]
    const dict = p.literal.dictionary
    const none = p.literal.not_set
    const state = options => ['state', {
        options: dict(Object.fromEntries(Object.entries(options).map(([id, value]) =>
            [id, { constraints: none(), description: none(), value }]))), results: none(),
    }]
    const stateResolver = options => ['state', { options: dict(options) }]
    const signature = entry(model.resolver.signatures.signatures, 'Root')
    const source = ['liana', {
        ...model,
        types: dict({
            Source: { 'root value': state({
                ready: ['group', dict({ label: { description: none(), value: ['simple', 'Text'] } })],
                other: ['nothing', null],
            }) },
            Root: { 'root value': state({ read: ['simple', 'Text'], skip: ['simple', 'Text'] }) },
        }),
        resolver: {
            signatures: { signatures: dict({
                Source: signature,
                Root: { ...signature, parameters: ['local', {
                    lookups: dict({}),
                    types: dict({ source: {
                        type: { location: ['internal', 'Source'] },
                        presence: ['required', null],
                    } }),
                }] },
            }) },
            types: dict({
                Source: { 'root value resolver': stateResolver({
                    ready: { constraints: dict({}), resolver: ['group', dict({ label: { resolver: ['simple', null] } })] },
                    other: { constraints: dict({}), resolver: ['nothing', null] },
                }) },
                Root: { 'root value resolver': stateResolver({
                    read: { constraints: dict({ ready: ['state', {
                        selection: {
                            start: ['parameter', 'source'],
                            tail: { path: p.literal.list([]) },
                        },
                        option: 'ready',
                    }] }), resolver: ['simple', null] },
                    skip: { constraints: dict({}), resolver: ['simple', null] },
                }) },
            }),
        },
    }]
    const rootSignature = entry(source[1].resolver.signatures.signatures, 'Root')
    const importedSource = ['liana', {
        ...source[1],
        imports: dict({ shared: source[1] }),
        types: dict({ Root: entry(source[1].types, 'Root') }),
        resolver: {
            signatures: { signatures: dict({ Root: {
                ...rootSignature,
                parameters: ['local', {
                    lookups: dict({}), types: dict({ source: {
                        type: { location: ['external', { import: 'shared', type: 'Source' }] },
                        presence: ['required', null],
                    } }),
                }],
            } }) },
            types: dict({ Root: entry(source[1].resolver.types, 'Root') }),
        },
    }]
    const bridge = {
        ...model,
        imports: dict({ deep: source[1] }),
        types: dict({ Source: { 'root value': ['component', {
            type: ['external', { import: 'deep', type: 'Source' }], results: none(),
        }] } }),
        root: 'Source',
        resolver: {
            signatures: { signatures: dict({ Source: signature }) },
            types: dict({ Source: { 'root value resolver': ['component', {
                location: ['external', {
                    'schema import': 'deep', 'resolver import': 'deep', signature: 'Source',
                }], arguments: none(), constraints: dict({}),
            }] } }),
        },
    }
    const rootResolver = entry(importedSource[1].resolver.types, 'Root')['root value resolver']
    const readOption = entry(rootResolver[1].options, 'read')
    const ready = entry(readOption.constraints, 'ready')
    const transitiveSource = ['liana', {
        ...importedSource[1], imports: dict({ shared: bridge }),
        resolver: {
            ...importedSource[1].resolver,
            types: dict({ Root: { 'root value resolver': ['state', {
                ...rootResolver[1],
                options: dict({
                    skip: entry(rootResolver[1].options, 'skip'),
                    read: { ...readOption, constraints: dict({ ready: ['state', {
                        ...ready[1], selection: {
                            ...ready[1].selection,
                            tail: { ...ready[1].selection.tail, path: p.literal.list([['component', null]]) },
                        },
                    }] }) },
                }),
            }] } }),
        },
    }]
    for (const schema of [source, importedSource, transitiveSource]) {
        const directory = mkdtempSync(join(tmpdir(), 'liana-next-metadata-'))
        try {
            const generated = pipeline(schema)
            assert.deepEqual(placeholders(generated.pareto), [])
            assert.equal(write(generated.typescript, directory).typescriptPlaceholders, 0)
            assert.deepEqual(typecheck(directory), { status: 'passed' })
            compile(directory)
            const parse = await import(pathToFileURL(join(directory, 'dist/schemas/unresolved/refiners/list_of_characters.js')))
            const resolve = await import(pathToFileURL(join(directory, 'dist/schemas/resolved/refiners/unresolved.js')))
            const serialize = await import(pathToFileURL(join(directory, 'dist/schemas/resolved/transformers/serialized_paragraph.js')))
            const authored = parse.Root(chars('| read "authored"'), abort, { 'tab size': 4 })
            assert.deepEqual(authored, ['read', 'authored'])
            const payload = { label: 'the node' }
            const resolved = resolve.Root(authored, abort, null, { source: ['ready', payload] })
            assert.deepEqual(resolved, ['read', { value: 'authored', meta: { ready: payload } }])
            assert.equal(resolved[1].meta.ready, payload)
            const serialized = serialize.Root(resolved, { indentation: '    ' }).__get_raw().join('\n')
            assert.doesNotMatch(serialized, /meta|the node|~/)
            assert.deepEqual(parse.Root(chars(serialized), abort, { 'tab size': 4 }), authored)
            assert.deepEqual(resolve.Root(['skip', 'ordinary'], abort, null, { source: ['other', null] }), ['skip', 'ordinary'])
            assert.throws(() => resolve.Root(authored, abort, null, { source: ['other', null] }),
                error => error.type === 'unexpected state option' && error.id === 'ready')
        } finally {
            rmSync(directory, { recursive: true })
        }
    }
})

test('accounting migrations retain their registry structure and explicit resolver corrections', () => {
    for (const name of ['boekhouding', 'boekhouding_oude_model']) {
        const source = readFileSync(new URL('../liana_registry/liana/' + name + '.liana.lna', base), 'utf8')
        const expected = readFileSync(new URL(name + '.liana_next.lna', examples), 'utf8')
        assert.equal(convert(source, { correctBoekhouding: name === 'boekhouding' }), expected)
        const next = fixture(name)
        assert.equal(next[0], name === 'boekhouding' ? 'liana' : 'astn')
        const generated = pipeline(next)
        assert.deepEqual(placeholders(generated.pareto), [])
    }
})

test('generated Boekhouding follows the proven bank-mutation and Resultaat lookup behavior', async () => {
    const directory = mkdtempSync(join(tmpdir(), 'liana-next-boekhouding-'))
    try {
        const generated = pipeline(fixture('boekhouding'))
        assert.equal(write(generated.typescript, directory).typescriptPlaceholders, 0)
        assert.deepEqual(typecheck(directory), { status: 'passed' })
        compile(directory)
        const resolver = await import(pathToFileURL(join(directory, 'dist/schemas/resolved/refiners/unresolved.js')))
        const dict = p.literal.dictionary
        const stamp = { Bedrag: 123, Datum: 20260101 }
        const bank = { Mutaties: dict({ payment: stamp }) }
        const account = { marker: 'Resultaat account' }
        const informal = { marker: 'Informal account' }
        const year = {
            Balans: {
                Verrekenposten: dict({}),
                Bankrekeningen: dict({ bank }),
                'Overige balans items': dict({ item: { marker: 'Balance item' } }),
                'Informele rekeningen': dict({ informal }),
            },
        }
        const parameters = {
            Jaarbeheer: year,
            Grootboekrekeningen: { Balans: dict({}), Resultaat: dict({ expense: account }) },
            Handelstransacties: { Inkopen: dict({}), Verkopen: dict({}) },
        }
        const processing = id => dict({ [id]: {
            Stam: null, type: ['Balans', ['Informele rekening', { 'Informele rekening': 'informal' }]],
        } })
        const source = {
            Verrekenposten: dict({}),
            Bankrekeningen: dict({ bank: { Stam: null, 'Mutatie Verwerkingen': processing('payment') } }),
            'Overige Balans Items': dict({ item: {
                Stam: null, 'Memoriaal Boekingen': dict({ booking: {
                    Bedrag: 123, Datum: 20260101, Omschrijving: 'Expense', Grootboekrekening: 'expense',
                } }),
            } }),
        }
        const output = resolver.Mutaties(source, abort, { Jaren: lookup.acyclic.from_resolved_dictionary(dict({})) }, parameters)
        const resolvedBank = entry(output.Bankrekeningen, 'bank')
        assert.equal(resolvedBank.Stam, bank)
        assert.equal(entry(resolvedBank['Mutatie Verwerkingen'], 'payment').Stam, stamp)
        assert.equal(entry(entry(output['Overige Balans Items'], 'item')['Memoriaal Boekingen'], 'booking').Grootboekrekening['l entry'], account)
        assert.throws(() => resolver.Mutaties({
            ...source, Bankrekeningen: dict({ bank: { Stam: null, 'Mutatie Verwerkingen': processing('absent') } }),
        }, abort, { Jaren: lookup.acyclic.from_resolved_dictionary(dict({})) }, parameters), error =>
            error.type === 'no benchmark entry' && error.id === 'absent')
    } finally {
        rmSync(directory, { recursive: true })
    }
})

test('the formerly blocked schemas emit explicit lookup conversion and forwarding', () => {
    const optionalLookups = expression => {
        assert.equal(expression[0], 'change context')
        const conversion = expression[1].callback
        assert.equal(conversion[0], 'convert')
        assert.equal(conversion[1].type[0], 'optional')
        const body = conversion[1].type[1][1]['on set']
        assert.equal(body[0], 'with bindings')
        const component = body[1].result[1].type
        assert.equal(component[0], 'component')
        assert.equal(component[1][0], 'transform')
        const arguments_ = component[1][1].arguments
        assert.equal(arguments_[0], 'resolver')
        assert.equal(arguments_[1].lookups[0], 'initialize')
        return arguments_[1].lookups[1]
    }
    const definitions = entry(pipeline(fixture('json_schema_light')).pareto.schemas, 'resolved')
    const resolver = entry(definitions.refiners, 'unresolved')
    const document = entry(resolver.implementations, 'Document').expression
    const root = entry(document[1], 'root value')
    assert.equal(entry(optionalLookups(root), 'definitions')[0], 'cyclic resolved dictionary')

    const pareto = entry(pipeline(fixture('programming_languages--pareto_next')).pareto.schemas, 'resolved')
    const transformer = entry(entry(pareto.refiners, 'unresolved').implementations, 'Transformer Root').expression
    const parameters = entry(transformer[1], 'parameters schema')
    assert.deepEqual(entry(optionalLookups(parameters), 'packages'), ['parameter', 'packages'])
})
